/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbooking;

import javax.swing.JComboBox;

/**
 *
 * @author iamhe
 */
public class MainMenu extends javax.swing.JFrame {

    private int roomChoice;
    private int mealChoice;
    private int duration;
    private String[] roomDropDownMenu = {"", "Single (1) [£50]", "Double (2) [75]", "Family (4) [£105]"};
    private String[] mealDropDownMenu = {"", "self-catering", "half-board", "full board"};

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {

        initComponents();

        roomSize.setModel(new javax.swing.DefaultComboBoxModel<>(roomDropDownMenu));
        mealService.setModel(new javax.swing.DefaultComboBoxModel<>(mealDropDownMenu));
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mealService = new javax.swing.JComboBox<>();
        roomSize = new javax.swing.JComboBox<>();
        headingTwo = new javax.swing.JLabel();
        headingOne = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mealService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealServiceActionPerformed(evt);
            }
        });
        getContentPane().add(mealService);
        mealService.setBounds(550, 290, 150, 20);

        roomSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomSizeActionPerformed(evt);
            }
        });
        getContentPane().add(roomSize);
        roomSize.setBounds(550, 190, 150, 20);

        headingTwo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headingTwo.setText("  Choose meal service:");
        getContentPane().add(headingTwo);
        headingTwo.setBounds(300, 280, 190, 30);

        headingOne.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headingOne.setText("     Choose room type:");
        getContentPane().add(headingOne);
        headingOne.setBounds(300, 180, 190, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/15e8fd101fe6a744c3a2fb7b5e092587.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1024, 682);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mealServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealServiceActionPerformed
        JComboBox jcmbType = (JComboBox) evt.getSource();
        String cmbType = (String) jcmbType.getSelectedItem();
        //System.out.println(cmbType);

        int x = 0;
        for (int i = 0; i < 4; i++) {
            if (mealDropDownMenu[i].equals(cmbType)) {
                x = i;
            }
        }
        switch (x) {
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;
            default:
                System.out.println("Error: Switch statement no functioning as intended");
        }

    }//GEN-LAST:event_mealServiceActionPerformed

    private void roomSizeActionPerformed(java.awt.event.ActionEvent evt) {
        JComboBox jcmbType = (JComboBox) evt.getSource();
        String cmbType = (String) jcmbType.getSelectedItem();
        //System.out.println(cmbType);

        int x = 0;
        for (int i = 0; i < 4; i++) {
            if (roomDropDownMenu[i].equals(cmbType)) {
                x = i;
            }
        }
        switch (x) {
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;
            default:
                System.out.println("Error: Switch statement no functioning as intended");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel headingOne;
    private javax.swing.JLabel headingTwo;
    private javax.swing.JComboBox<String> mealService;
    private javax.swing.JComboBox<String> roomSize;
    // End of variables declaration//GEN-END:variables
}
